dataset: cifar10
num_classes: 10
img_size: 224
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
amp: True
epochs: 50
cooldown_epochs: 10
warmup_epochs: 10
patience_epochs: 10
batch_size: 128
lr: 3e-4
min_lr: 1e-5
warmup_lr: 1e-6
sched: cosine
weight_decay: 0.05
opt: adamw
smoothing: 0.1
model: convmlp_s_classification
pretrained: True
model_ema: False
hflip: 0.5
vflip: 0.0
ratio:
    - 0.75
    - 1.3333333333333333
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
recount: 1
remode: pixel
reprob: 0.25
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
cutmix: 1.0
